---
- name: Create directories
  file:
    state: directory
    path: "{{ item }}"
    mode: 0755
  with_items:
    - /etc/loki
    - /etc/promtail
    - /opt/docker-compose-service/loki

- name: Put GCP credentials.json
  copy:
    src: credentials.json
    dest: /etc/loki/credentials.json
    mode: 0644
  notify: Restart loki
  when: loki_unuse_iam == true and loki_store == "gcs"

- name: Put docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: /opt/docker-compose-service/loki/docker-compose.yml
    mode: 0644
  notify: Restart loki

- name: Put loki-config.yml
  template:
    src: loki-config.yml.j2
    dest: /etc/loki/config.yml
  notify: Restart loki

- name: Put promtail-config.yml
  template:
    src: promtail-config.yml.j2
    dest: /etc/promtail/config.yml
  notify: Restart loki

- name: Start loki
  systemd:
    name: docker-compose-service@loki
    enabled: yes
    state: started
    daemon_reload: yes

- name: Check caddy conf
  uri:
    url: http://localhost:2019/id/{{ loki_host }}/
    method: GET
    headers:
      Content-Type: application/json
      Origin: http://localhost:2019
    status_code:
      - 200
      - 404

- name: Delete caddy conf
  uri:
    url: http://localhost:2019/id/{{ loki_host }}/
    method: DELETE
    headers:
      Content-Type: application/json
      Origin: http://localhost:2019
    status_code:
      - 200
      - 404

- name: Update caddy
  uri:
    url: http://localhost:2019/config/apps/http/servers/{{ caddy_servername }}/routes/
    method: POST
    headers:
      Content-Type: application/json
      Origin: http://localhost:2019
    return_content: yes
    status_code: 200
    body_format: json
    body: |
      {
        "@id": "{{ loki_host }}",
        "match": [
          {
            "host": [
              "{{ loki_host }}"
            ]
          }
        ],
        "handle": [
          {
            "handler": "subroute",
            "routes": [
              {
                "match": [
                  {
                    "header": {
                      "X-Scope-OrgID": [{{ loki_org_ids }}]
                    },
                    "path": [
                      "/*"
                    ]
                  }
                ],
                "handle": [
                  {
                    "handler": "reverse_proxy",
                    "upstreams": [
                      {
                        "dial": "loki:3100"
                      }
                    ]
                  }
                ]
              },
              {
                "match": [
                  {
                    "header": {
                      "X-Scope-OrgID": ["*"]
                    },
                    "path": [
                      "/*"
                    ]
                  },
                  {
                    "header": {
                      "X-Scope-OrgID": null
                    },
                    "path": [
                      "/*"
                    ]
                  }
                ],
                "handle": [
                  {
                    "handler": "static_response",
                    "status_code": "400",
                    "body": ":)"
                  }
                ]
              }
            ]
          }
        ],
        "terminal": true
      }